root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "/go/bin/main"                      # Local onde o binário será gerado
  cmd = "go build -o /go/bin/main ./cmd/api/main.go" # Caminho principal do projeto
  delay = 1000                              # Delay entre detecção de mudança e build
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["internal", "cmd"]         # Diretórios importantes para monitoramento
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "10s"
  log = "build-errors.log"                  # Registro de erros de compilação
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false                     # Continua monitorando mesmo após erro

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
