version: '3.8'

volumes:
  logs:
    driver: local
  db_data:
    driver: local

x-common-variables: &common-variables
  TZ: America/Sao_Paulo

services:
  db:
    container_name: extensao_db
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: extensao_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - extensao_network

  phpmyadmin:
    container_name: extensao_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      <<: *common-variables
      PMA_HOST: extensao_db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - extensao_network

  api:
    container_name: extensao_api
    build:
      context: ./extensao-web-api
      dockerfile: Dockerfile
    environment:
      DB_HOST: extensao_db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: extensao_database
      JWT_SECRET: seu_segredo_muito_seguro_aqui
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./extensao-web-api:/app
    command: ["air"]
    networks:
      - extensao_network
      
networks:
  extensao_network: